server:
    port: 8081

spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://localhost:5432/finpay
        username: finpay
        password: finpay
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
      oauth2:
        authorizationserver:
          jwt:
            private-key-location: classpath:keys/private.pem
            public-key-location: classpath:keys/public.pem