services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: finpay
            POSTGRES_USER: finpay
            POSTGRES_PASSWORD: finpay
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=finpay
            - PGADMIN_CONFIG_SERVER_MODE=False
        ports:
            - "5050:80"
        depends_on:
            - postgres
    redis:
        image: redis:7
        ports:
            - "6379:6379"

    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"

    kafka:
        image: bitnami/kafka:3.7
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
volumes:
    postgres_data: