services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: finpay
            POSTGRES_USER: finpay
            POSTGRES_PASSWORD: finpay
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=finpay
            - PGADMIN_CONFIG_SERVER_MODE=False
        ports:
            - "5050:80"
        depends_on:
            - postgres
    redis:
        image: redis:7
        ports:
            - "6379:6379"

    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"

    kafka:
        image: confluentinc/cp-kafka:7.6.0
        hostname: kafka
        container_name: kafka
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            # Enable JMX for Kafka
            KAFKA_JMX_PORT: 9999
            KAFKA_JMX_HOSTNAME: kafka
            KAFKA_OPTS: -Djava.rmi.server.hostname=kafka
        ports:
            - "9092:9092"
            - "9999:9999"
        depends_on:
            - zookeeper
    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin

    kafka-jmx-exporter:
      image: bitnami/jmx-exporter:latest
      platform: linux/arm64
      ports:
        - "7071:5556"
      environment:
        - SERVICE_PORT=5556
      volumes:
        - ./kafka-jmx.yml:/etc/jmx-exporter/config.yml
      command: 5556 /etc/jmx-exporter/config.yml
      depends_on:
        - kafka

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - ./elasticsearch-data:/usr/share/elasticsearch/data

    kibana:
      image: docker.elastic.co/kibana/kibana:8.10.2
      container_name: kibana
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch

    logstash:
      image: docker.elastic.co/logstash/logstash:8.10.2
      container_name: logstash
      ports:
        - "5001:5000"
      volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      depends_on:
        - elasticsearch