server:
    port: 8080

spring:
    application:
        name: gateway
    cloud:
      gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:8080"
                - "http://localhost:5173"
                - "http://localhost:5174"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
    data:
      redis:
        host: localhost
        port: 6379

resilience4j:
  circuitbreaker:
    instances:
      transactionCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
  timelimiter:
    instances:
      transactionCB:
        timeoutDuration: 5s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs/gateway
        name: api-gateway-docs
      - url: /v3/api-docs/auth
        name: auth-docs
      - url: /v3/api-docs/account
        name: account-docs
      - url: /v3/api-docs/transaction
        name: transaction-docs
      - url: /v3/api-docs/notification
        name: notification-docs
      - url: /v3/api-docs/fraud
        name: fraud-docs
    urls-primary-name: api-gateway-docs
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG